#' Lung Cancer Simulated Dataset
#'
#' A semi-synthetic dataset constructed from the CALGB 9633 clinical trial and
#' an EHR-derived real-world data source. The dataset includes both internal
#' and external treated and control groups, enabling evaluation of methods for
#' hybrid controlled trials, data fusion between randomized trials and
#' observational studies, and generalization of treatment effect.
#'
#' @format A data frame with 16552 rows and 19 variables:
#' \describe{
#'   \item{patid}{Patient ID (numeric, anonymized)}
#'   \item{cohort}{Data source: \code{"C9633"} for RCT cohort, \code{"EHR"} for
#'   external observational cohort}
#'   \item{treat}{Treatment assignment: 1 = treated, 0 = control}
#'   \item{survtime}{Observed survival time in years}
#'   \item{survcens}{Event indicator: 1 = event observed, 0 = right-censored}
#'   \item{sex}{Patient sex: 1 = male, 0 = female}
#'   \item{age}{Age at diagnosis}
#'   \item{race}{Race: 1 = White, 0 = Non-White}
#'   \item{hist}{Tumor histology: 1 = squamous, 0 = others}
#'   \item{tsize}{Tumor size (in centimeters)}
#'   \item{ps}{Performance status (0/1); available only in C9633 cohort}
#'   \item{symptoms}{Presence of baseline symptoms (0/1); available only in
#'   C9633 cohort}
#'   \item{weightloss}{Recent weight loss (0/1); available only in C9633 cohort}
#'   \item{FACILITY}{Facility type: 1 = community, 2 = comprehensive community,
#'   3 = academic/research, 4 = integrated network; available only in EHR cohort}
#'   \item{income}{Quartile of ZIP-code-level median household income (1 =
#'   lowest, 4 = highest); available only in EHR cohort}
#'   \item{charlson}{Charlson comorbidity index (0–3); available only in EHR
#'   cohort}
#'   \item{diagyear}{Year of initial diagnosis (2006–2012); available only in
#'   EHR cohort}
#'   \item{insurance}{Primary insurance at diagnosis; available only in EHR cohort}
#'   \item{travel}{Travel distance to treating facility: 1 = <10 miles,
#'   2 = 10–50 miles, 3 = >50 miles; available only in EHR cohort}
#' }
#'
#' @details
#' This data set was simulated based on the CALGB 9633 trial and an
#' EHR-derived cohort, stratified by cohort and treatment groups.
#'
#' All variables other than \code{patid}, \code{cohort}, \code{treat},
#' \code{survtime}, and \code{survcens} are baseline covariates measured prior
#' to treatment initiation.
#'
#' Baseline covariates were simulated using the \pkg{synthpop} package, which by
#' default uses Classification and Regression Trees (CART) to synthesize each
#' variable conditionally on the previously simulated ones. This sequential
#' approach preserves marginal distributions and dependency structures.
#'
#' Survival outcomes were generated by fitting a survival random forest model
#' on the original data within each \code{cohort}–\code{treat} group. For each
#' simulated subject, survival time was predicted using their simulated
#' covariates. Independent uniform censoring was applied.
#'
#' **Potential Survival Time:** This data set only includes observed survival time
#' subject to right censoring. The ground-truth potential survival times for
#' each individual are available separately in the data frame \code{lungcancer_truth}.
#'
#' **Privacy Protection:** To ensure patient confidentiality, no row in this
#' data set exactly matches any row in the original data sources. All values are
#' simulated, not observed, and the data set has been rigorously de-identified.
#'
#' **Code Availability:** The code used to generate this data set is available
#' upon request to the package author.
#'
#'
#' @references
#' If you use this dataset, please cite:
#'
#' Ke Zhu, Shu Yang, and Xiaofei Wang. (2025). *Enhancing Statistical Validity and Power in Hybrid Controlled Trials: A Randomization Inference Approach with Conformal Selective Borrowing*. In *Proceedings of the 42nd International Conference on Machine Learning (ICML)*.
#'
#' @examples
#' summary(lungcancer)
#' summary(lungcancer_truth)
#'
#' # library(summarytools)
#' # view(dfSummary(lungcancer))
#' # view(dfSummary(lungcancer_truth))
"lungcancer"
